# Generated by Django 2.1.7 on 2019-03-26 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('totalsum', models.CharField(max_length=100)),
                ('mealsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Meals')),
            ],
        ),
        migrations.CreateModel(
            name='MealsToOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('mealsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Meals')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablesname', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('mealsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Meals')),
                ('statusid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Statuses')),
                ('tablesid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Tables')),
                ('waiterid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=15)),
            ],
        ),
        migrations.AddField(
            model_name='mealstoorders',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Orders'),
        ),
        migrations.AddField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Orders'),
        ),
        migrations.AddField(
            model_name='checks',
            name='percentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ServicePercentage'),
        ),
    ]
